import { logger } from "./logger.js";

// import OpenAI from "openai";
// import fs from "fs";
// import path from "path";
// import playSound from "play-sound";

// const openai = new OpenAI();
// const player = playSound({});

// export const tts = async (text) => {
//   return new Promise(async (resolve, reject) => {
//     try {
//       logger.info(`Starting TTS process for text: "${text}"`);

//       const response = await openai.audio.speech.create({
//         model: "tts-1",
//         voice: "nova",
//         input: text,
//         speed: 0.9,
//       });
//       logger.info("Received response from OpenAI TTS API");

//       const buffer = Buffer.from(await response.arrayBuffer());
//       logger.info("Converted response to buffer");

//       const tempFilePath = path.resolve(
//         `./temp/audio-${Math.floor(Math.random() * 1e3)}.mp3`
//       );
//       logger.info(`Generated temp file path: ${tempFilePath}`);

//       fs.writeFileSync(tempFilePath, buffer);
//       logger.info(`Audio file written to disk at: ${tempFilePath}`);

//       player.play(tempFilePath, (error) => {
//         if (error) {
//           logger.error(`Error playing audio: ${error}`);
//           fs.unlinkSync(tempFilePath);
//           logger.info(`Deleted temp file: ${tempFilePath}`);
//           reject(error);
//         } else {
//           logger.info("Audio played successfully");
//           fs.unlinkSync(tempFilePath);
//           logger.info(`Deleted temp file: ${tempFilePath}`);
//           resolve();
//         }
//       });
//     } catch (error) {
//       logger.error(`Error in TTS process: ${error}`);
//       reject(error);
//     }
//   });
// };

const client = new ElevenLabsClient({
  apiKey: process.env.ELEVENLABS_API_KEY,
});

import { ElevenLabsClient, play } from "elevenlabs";
export const tts = async (text) => {
  logger.info(`Starting TTS process using ElevenLabs for text: "${text}"`);
  const audio = await client.generate({
    voice: "Jessica",
    text,
    model_id: "eleven_multilingual_v2",
    voice_settings: {
      stability: 0.7,
      similarity_boost: 0.9,
      style: 0.25,
    },
  });
  logger.info("Audio generated by ElevenLabs");

  await play(audio);
  logger.info("Audio played successfully using ElevenLabs");
};
